CREATE TABLE job_offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    company VARCHAR(255),
    link VARCHAR(1024),
    description TEXT,
    location VARCHAR(255),
    published_date DATE
);

CREATE INDEX idx_job_offer_title ON job_offer(title);
