ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS direct_link VARCHAR(500);
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS published_date DATE;
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS first_seen DATE;
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS last_seen DATE;
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS source_link VARCHAR(500);
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
